In [1]:
import numpy as np
from scipy.stats import binned_statistic, binned_statistic_2d, binned_statistic_dd

In [2]:
# Make some bins and random data

dx = 0.2
xmin = 0.
nbins = 5
npoints = 100
bin_edges_x = np.arange(xmin, dx*nbins + dx, dx)
print(bin_edges_x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [3]:
x = np.random.rand(npoints) # random between 0 and 1
y = np.random.rand(npoints) + 1. # random between 1 and 2
bin_edges_y = bin_edges_x + 1.

In [4]:
# bin y based on corresponding x bins and compute a statistic for each binned y array
bin_stat = binned_statistic(x, y, bins = nbins, statistic = 'mean')

In [5]:
# bin_stat has the statistic array (nbins,) of means, the bin_edges (nbins+1,) and binnumber array (npoints, ) 
# which contains the bin id of every point in the binned y array
bin_stat

BinnedStatisticResult(statistic=array([1.63376722, 1.45585101, 1.51615264, 1.59745027, 1.42216428]), bin_edges=array([0.00938742, 0.20710086, 0.40481429, 0.60252773, 0.80024117,
       0.99795461]), binnumber=array([2, 1, 5, 4, 4, 2, 4, 4, 3, 5, 4, 5, 5, 2, 2, 1, 3, 1, 2, 3, 3, 4,
       3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 1, 4, 3, 1, 3, 1, 3, 2, 3, 2, 5, 4,
       4, 1, 2, 5, 3, 3, 1, 3, 5, 2, 1, 3, 5, 2, 3, 4, 4, 4, 3, 5, 4, 5,
       4, 4, 5, 2, 5, 1, 4, 1, 2, 5, 3, 5, 2, 4, 5, 3, 2, 2, 1, 2, 5, 2,
       1, 2, 1, 4, 3, 5, 2, 5, 3, 5, 1, 5]))

In [6]:
# using the resulting binnumber to bin the x array shows that the binnumber corresponds to x bins:

binned_x = np.array([x[bin_stat.binnumber == i] for i in range(1, len(bin_edges_x))])
binned_x

/home/earthwave/miniconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


array([array([0.02312967, 0.05118469, 0.13648097, 0.20316861, 0.15859225,
       0.08289751, 0.00938742, 0.0477316 , 0.10570608, 0.01544491,
       0.03173148, 0.14648337, 0.01840557, 0.18619345, 0.20137931]),
       array([0.28112461, 0.20779931, 0.36433646, 0.21099533, 0.23839216,
       0.28194952, 0.2857064 , 0.27430598, 0.3443361 , 0.34641834,
       0.24208006, 0.36591723, 0.24539127, 0.30565465, 0.23968577,
       0.32489979, 0.31929907, 0.290857  , 0.24033445]),
       array([0.49857564, 0.51189027, 0.43268097, 0.47397668, 0.56224036,
       0.46196704, 0.60226305, 0.46431964, 0.55723223, 0.48116758,
       0.57771894, 0.48552536, 0.49916581, 0.57314334, 0.4413105 ,
       0.55056782, 0.55272082, 0.47439415, 0.4205169 , 0.48438799,
       0.47273573, 0.43112041, 0.50550967, 0.42433054, 0.54834392,
       0.54893384]),
       array([0.722912  , 0.61135238, 0.63747237, 0.60642599, 0.78997994,
       0.70359471, 0.79638728, 0.79362651, 0.68595046, 0.63467836,
       0.61944   , 0.

In [7]:
# So using the same binnumber to bin y values gives us y binned by x
binned_y = np.array([y[bin_stat.binnumber == i] for i in range(1, len(bin_edges_x))])
binned_y

/home/earthwave/miniconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([array([1.82273343, 1.7175696 , 1.10060314, 1.91308713, 1.43492746,
       1.94152529, 1.82069722, 1.43793883, 1.61240145, 1.40609489,
       1.781968  , 1.48851699, 1.36244573, 1.79337445, 1.87262463]),
       array([1.74058909, 1.40233784, 1.70253763, 1.19159723, 1.47324656,
       1.34402303, 1.61007948, 1.228282  , 1.07682672, 1.89310293,
       1.91281443, 1.46971922, 1.7321487 , 1.96194613, 1.17866671,
       1.51806355, 1.00045189, 1.11992309, 1.10481297]),
       array([1.50515427, 1.50351091, 1.74566586, 1.49852242, 1.07897524,
       1.97193839, 1.49766598, 1.44077815, 1.73825541, 1.02093234,
       1.34163332, 1.63797067, 1.82928075, 1.8322159 , 1.49943438,
       1.21902387, 1.53937324, 1.36898124, 1.53245531, 1.23148715,
       1.91010078, 1.40884633, 1.3381201 , 1.98503275, 1.37410567,
       1.37050811]),
       array([1.45784731, 1.94192136, 1.9360683 , 1.92299325, 1.7238491 ,
       1.78236345, 1.58648639, 1.65680912, 1.93501203, 1.68272757,
       1.95976416, 1.

In [8]:
# We can recover the bin_stat.statistic array by computing the mean inside each of these bins:

print(bin_stat.statistic)
print([np.mean(i) for i in binned_y])

[1.63376722 1.45585101 1.51615264 1.59745027 1.42216428]
[1.6337672154148624, 1.455851010503185, 1.5161526363958917, 1.5974502689370556, 1.4221642795142753]


In [9]:
# Compute a third array based on x and y:
z = np.random.rand(npoints) + 2.
bin_edges_z = bin_edges_x + 2.

# Now we can bin this in both x and y using binned_statistic_2d:
bin_stat_2d = binned_statistic_2d(x, y, z, statistic='mean', 
                                  bins=[bin_edges_x, bin_edges_y], expand_binnumbers=True)

In [10]:
bin_stat_2d.statistic.shape

(5, 5)

In [11]:
# here we have the same problem as before, where we don't know which way to read the array :) 
# So I'll modify this so that we only have 4 y bins, to make it easier to see

bin_stat_2d = binned_statistic_2d(x, y, z, statistic='mean', 
                                  bins=[bin_edges_x, bin_edges_y[:-1]], expand_binnumbers=True)

In [12]:
print(bin_stat_2d.statistic.shape)
print(bin_stat_2d.statistic)

(5, 4)
[[2.10124378 2.3224929  2.59528203 2.55645253]
 [2.4321531  2.64772109 2.30146059 2.46295536]
 [2.5689888  2.45029478 2.72362489 2.55353154]
 [2.21308382 2.54473492 2.36391868 2.56725941]
 [2.3376162  2.45164533 2.42089424 2.63156451]]


In [13]:
print(bin_stat_2d.statistic[0]) # the first x bin, containing the 4 y bins
print(bin_stat_2d.statistic[:, 0]) # the first y bin, containing the 5 x bins

[2.10124378 2.3224929  2.59528203 2.55645253]
[2.10124378 2.4321531  2.5689888  2.21308382 2.3376162 ]


In [14]:
# Compute a fourth array, and lets bin in 3d using binned_statistic_dd
r = x**2+ y**2 +z**2

# Provide the x, y, z arrays - this would be of shape (3, npoints), so we need to transpose it to get 
# it into shape (npoints, 3) as required

bin_stat_dd = binned_statistic_dd(np.array([x, y, z]).T, r, statistic='mean', 
                                  bins=np.array([bin_edges_x, bin_edges_y[:-1], bin_edges_z]))

/home/earthwave/miniconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [15]:
bin_stat_dd.statistic.shape

(5, 4, 5)

In [16]:
print(bin_stat_dd.statistic[0]) # the first x bin, containing the 4 y bins and 5 z bins
print(bin_stat_dd.statistic[0][0]) # the first x bin and y bin, containing the 5 z bins
print(bin_stat_dd.statistic[:, 0]) # the first y bin, containing the 5 x bins and the 5 z bins
print(bin_stat_dd.statistic[:, :, 0]) # the first z bin, containing the 5 x bins and the 4 y bins

[[ 5.64517976         nan         nan         nan         nan]
 [        nan  7.25057042         nan         nan         nan]
 [        nan  7.63728954         nan  9.857915   10.39197591]
 [        nan  8.14658359         nan 10.71955372 11.43960962]]
[5.64517976        nan        nan        nan        nan]
[[5.64517976        nan        nan        nan        nan]
 [5.6538057  7.13034627 7.83356843 8.7640143         nan]
 [       nan 6.37369926        nan        nan 9.77290188]
 [       nan 6.56652897        nan        nan        nan]
 [6.38375388 7.10861736 8.29002943 9.02651407        nan]]
[[5.64517976        nan        nan        nan]
 [5.6538057         nan 6.76975363        nan]
 [       nan 6.73718884        nan        nan]
 [       nan 6.74152587 7.05435286 7.81626881]
 [6.38375388        nan        nan        nan]]
